# Generated by Django 4.0 on 2021-12-30 07:57

import apps.video.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_file', models.FileField(blank=True, null=True, upload_to=apps.video.models.video_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'AVI', 'MKV', '3GP'])])),
                ('name', models.CharField(max_length=64)),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converted/')),
                ('target_format', models.CharField(choices=[('MP4', 'mp4'), ('AVI', 'avi'), ('MKV', 'mkv'), ('3GP', '3gp')], max_length=3)),
                ('length', models.DurationField()),
                ('convert_status', models.CharField(choices=[('INQ', 'in queue'), ('ERR', 'failed'), ('CNV', 'converting'), ('FIN', 'finished'), ('EXP', 'expired')], default='INQ', max_length=3)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('start_convert_date', models.DateTimeField(blank=True, null=True)),
                ('finish_convert_date', models.DateTimeField(blank=True, null=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auth.user')),
            ],
            options={
                'db_table': 'videos',
                'managed': True,
            },
        ),
    ]
