# Generated by Django 4.0 on 2021-12-30 09:09

import apps.video.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='convert_status',
            field=models.CharField(choices=[('INQ', 'in queue'), ('ERR', 'failed'), ('CNV', 'converting'), ('FIN', 'finished'), ('EXP', 'expired')], default='INQ', max_length=3, verbose_name='convert status'),
        ),
        migrations.AlterField(
            model_name='video',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='converted/', verbose_name='converted file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='finish_convert_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finish convertion date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.DurationField(verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=64, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='video',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.video.models.video_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MP4', 'AVI', 'MKV', '3GP'])], verbose_name='source file'),
        ),
        migrations.AlterField(
            model_name='video',
            name='start_convert_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start convertion date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='target_format',
            field=models.CharField(choices=[('MP4', 'mp4'), ('AVI', 'avi'), ('MKV', 'mkv'), ('3GP', '3gp')], max_length=3, verbose_name='target format'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='auth.user', verbose_name='uploader'),
        ),
    ]
